{
 "title": "Orders Service",
 "tags": [ "orders" ],
 "refresh": "5s",
 "panels": [
  {
   "title": "HTTP Requests / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "{{method}} {{path}} {{status}}" }
   ]
  },
  {
   "title": "Outbox Pending",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "outbox_pending_total", "legendFormat": "Pending" }
   ]
  },
  {
   "title": "Kafka Events / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(kafka_events_processed_total[1m])",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "HTTP p95 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m]))",
     "legendFormat": "p95 {{path}}"
    }
   ]
  }
 ]
}